  
ALTER TABLE products ADD COLUMN IF NOT EXISTS weight INTEGER DEFAULT 0;  
ALTER TABLE products ADD COLUMN IF NOT EXISTS length INTEGER DEFAULT 0;  
ALTER TABLE products ADD COLUMN IF NOT EXISTS width INTEGER DEFAULT 0;  
ALTER TABLE products ADD COLUMN IF NOT EXISTS height INTEGER DEFAULT 0;  
  
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS weight INTEGER DEFAULT 0;  
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS length INTEGER DEFAULT 0;  
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS width INTEGER DEFAULT 0;  
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS height INTEGER DEFAULT 0; 
